api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 5001
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--blobstorage
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
      - name: connectionstrings--redis
        value: Redis:6379
      - name: connectionstrings--search
        value: '{{ securedParameter "Search" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: SocialService
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: Kestrel__Endpoints__http__Url
            value: http://*:5001
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__BlobStorage
            secretRef: connectionstrings--blobstorage
          - name: ConnectionStrings__Redis
            secretRef: connectionstrings--redis
          - name: ConnectionStrings__Search
            secretRef: connectionstrings--search
    scale:
      minReplicas: 1
tags:
  azd-service-name: SocialService
  aspire-resource-name: SocialService
