api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 5005
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--mongo
        value: mongodb://admin:{{ securedParameter "Mongo_password" }}@Mongo:27017?authSource=admin&authMechanism=SCRAM-SHA-256
      - name: connectionstrings--sqlserver
        value: Server=SqlServer,1433;User ID=sa;Password={{ securedParameter "SqlServer_password" }};TrustServerCertificate=true
  template:
    containers:
      - image: {{ .Image }}
        name: TrainingService
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: Kestrel__Endpoints__http__Url
            value: http://*:5005
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__Mongo
            secretRef: connectionstrings--mongo
          - name: ConnectionStrings__SqlServer
            secretRef: connectionstrings--sqlserver
    scale:
      minReplicas: 1
tags:
  azd-service-name: TrainingService
  aspire-resource-name: TrainingService
