// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingService.Connections.Database;

#nullable disable

namespace TrainingService.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20250830125248_SeedExercises")]
    partial class SeedExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.Property<Guid>("ExercisesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExercisesId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseWorkout");
                });

            modelBuilder.Entity("TrainingService.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuscleGroups")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequiresWeight")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96400"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 73,
                            Name = "Supino Reto",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96401"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 74,
                            Name = "Supino Inclinado",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96402"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 76,
                            Name = "Supino Declinado",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96403"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 73,
                            Name = "Supino com Halteres",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96404"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 65,
                            Name = "Crucifixo com Halteres",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96405"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 65,
                            Name = "Crucifixo no Cabo (Peck-Deck/Crossover)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96406"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 79,
                            Name = "Flexão de Braço",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96407"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 73,
                            Name = "Flexão Diamante",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96408"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 73,
                            Name = "Supino Fechado",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96409"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 9264,
                            Name = "Puxada na Frente (Pulldown)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640a"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 9776,
                            Name = "Barra Fixa (Pronada)",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640b"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 9264,
                            Name = "Barra Fixa (Supinada)",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640c"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 14384,
                            Name = "Remada Curvada com Barra",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640d"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 10288,
                            Name = "Remada Unilateral com Halter",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640e"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 10288,
                            Name = "Remada Baixa (Cabo)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9640f"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 9217,
                            Name = "Pullover (Cabo/Halter)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96410"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 791072,
                            Name = "Levantamento Terra",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96411"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 712,
                            Name = "Desenvolvimento Militar (Barra)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96412"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 200,
                            Name = "Desenvolvimento com Halteres",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96413"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 640,
                            Name = "Elevação Lateral",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96414"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 64,
                            Name = "Elevação Frontal",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96415"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1792,
                            Name = "Elevação Posterior (Peck-Deck Inverso)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96416"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1792,
                            Name = "Face Pull",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96417"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 704,
                            Name = "Remada Alta",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96418"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1568,
                            Name = "Encolhimento",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96419"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 48,
                            Name = "Rosca Direta (Barra)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641a"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 48,
                            Name = "Rosca Alternada (Halteres)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641b"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 48,
                            Name = "Rosca Martelo",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641c"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 48,
                            Name = "Rosca Scott",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641d"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 48,
                            Name = "Rosca Inversa",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641e"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 16,
                            Name = "Rosca Concentrada",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9641f"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 72,
                            Name = "Tríceps Testa",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96420"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 40,
                            Name = "Tríceps Corda",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96421"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 8,
                            Name = "Tríceps Francês (Halter)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96422"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 73,
                            Name = "Paralelas (Dips)",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96423"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 264,
                            Name = "Kickback de Tríceps",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96424"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 921600,
                            Name = "Agachamento Livre",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96425"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 918528,
                            Name = "Agachamento Frontal (Front Squat)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96426"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 655360,
                            Name = "Hack Squat",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96427"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 917504,
                            Name = "Leg Press 45°",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96428"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 917504,
                            Name = "Passada (Avanço)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96429"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 131072,
                            Name = "Cadeira Extensora",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642a"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 262144,
                            Name = "Mesa Flexora",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642b"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 790528,
                            Name = "Stiff (Terra Romeno)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642c"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 918016,
                            Name = "Levantamento Terra Sumo",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642d"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 790528,
                            Name = "Elevação Pélvica",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642e"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1966080,
                            Name = "Subida no Banco",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9642f"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1048576,
                            Name = "Panturrilha em Pé (Máquina)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96430"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1048576,
                            Name = "Panturrilha Sentado",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96431"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 786432,
                            Name = "Elevação de Quadril no Cabo",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96432"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 2129920,
                            Name = "Flexão de Quadril (Cabo)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96433"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 16384,
                            Name = "Abdominal Supra",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96434"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 2129920,
                            Name = "Abdominal Infra",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96435"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 2129920,
                            Name = "Elevação de Pernas",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96436"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 114688,
                            Name = "Prancha",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96437"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 114688,
                            Name = "Prancha Lateral",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96438"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 2211840,
                            Name = "Ab Wheel (Roda)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96439"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 81920,
                            Name = "Russian Twist",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643a"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 2195456,
                            Name = "Mountain Climbers",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643b"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 32,
                            Name = "Rosca de Punho",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643c"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 32,
                            Name = "Rosca de Punho Inversa",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643d"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1966624,
                            Name = "Farmer's Walk",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643e"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 4194303,
                            Name = "Burpee",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc9643f"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 823360,
                            Name = "Kettlebell Swing",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96440"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 4194303,
                            Name = "Clean and Press (Haltere/Barra)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96441"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 10288,
                            Name = "Puxada Neutra (Triângulo)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96442"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 14352,
                            Name = "Remada Cavalinho (T-Bar)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96443"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 66,
                            Name = "Crucifixo Inclinado",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96444"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 9728,
                            Name = "Pulldown com Barra Reta (Pulldown no Cabo)",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96445"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 200,
                            Name = "Desenvolvimento Arnold",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96446"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 790528,
                            Name = "Good Morning",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96447"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 1966080,
                            Name = "Box Jump",
                            RequiresWeight = false,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc96448"),
                            CreatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuscleGroups = 917504,
                            Name = "Afundo Búlgaro",
                            RequiresWeight = true,
                            UpdatedAt = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TrainingService.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestingTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.HasOne("TrainingService.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingService.Workouts.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
